import "./globals.css";
import "@aws-amplify/ui-react/styles.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { AmplifyProvider } from "@/components/amplify-provider";
import { AuthProvider } from "@/components/auth-provider";
import { Header } from "@/components/header";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={geist.className}>
        <AmplifyProvider>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </AmplifyProvider>
      </body>
    </html>
  );
}
